sturmf/regatta-angular2

backend/Makefile, e2e_tests/Makefile, frontend/Makefile, tmux.sh
* Makefiles for backend, frontend and e2e_tests
* bash script to run them in a tmux session
* start with `./tmux.sh`
=> Towards single script development startup

.travis.yml, backend/Makefile, e2e_tests/Makefile, frontend/Makefile
With this change we use the same Makefile based commands in travis so that we don't have to duplicate that configuration.
=> Move to makefile in travis

.travis.yml, backend/Makefile, e2e_tests/Makefile, frontend/Makefile, frontend/pubspec.yaml, frontend/test/example_test.dart
First step at implementing dart based tests
=> Angular testing

frontend/pubspec.yaml, frontend/test/example_test.dart
We no longer need an external package for this.
=> Small fix to use now built in package for testing.

backend/events/admin.py, frontend/lib/event_list_component.html
Having the input field at the top of the page feels more natural to me.
@sturmf : what do you think about that change?
=> move input field and add button before list

.travis.yml, frontend/Makefile, frontend/pubspec.yaml, frontend/test/example_test.dart
The tests finally work all together, unfortunately I had to add sleeps, but I think we can reduce their time significantly. But I had no time to test smaller values.
=> Unit test list component

frontend/test/example_test.dart
uses .querySelector() and .text on DummyComponent
=> Dummy Component test which queries for text

.travis.yml, frontend/.analysis_options, frontend/.idea/frontend.iml, frontend/Makefile, frontend/lib/event_list_component_po.dart, frontend/pubspec.yaml, frontend/test/event_list_test.dart, frontend/test/example_test.dart
Now the dummy test uses a real PageObject, this looks nice! Except that I for now had to rename the expected tagname. Will work on this next.
=> First working pageobject version.

e2e_tests/regatta-spec.js, frontend/lib/event_list_component.dart, frontend/lib/event_list_component.html, frontend/pubspec.yaml, frontend/web/index.html
First implementation with a angular2_material component and working enter key in input.
=> Material components REG-32 REG-34

frontend/.idea/frontend.iml, frontend/lib/app_component.dart, frontend/lib/app_component.html, frontend/lib/event_list_component.html, frontend/lib/navigation_bar_component.dart, frontend/lib/navigation_bar_component.html
This is the first prototype of a nav bar. There are no real nice angular material elements for this yet.
=> Reg 36 add navigation bar

.travis.yml, e2e_tests/regatta-spec.js, frontend/lib/event_list_component.html, frontend/pubspec.yaml
=> Reg 40 fix protractor event list selection

.travis.yml, e2e_tests/page_objects/event_list.page.js, e2e_tests/regatta-spec.js, frontend/lib/event_list_component.html, frontend/pubspec.yaml, tmux.sh
Refactor protractor test by using page object for event list.
=> Reg-42 page object for protractor

e2e_tests/page_objects/event_list.page.js, frontend/lib/event_list_component.dart, frontend/lib/event_list_component.html, frontend/lib/services/event_service.dart, frontend/lib/store/action_type.dart, frontend/lib/store/regatta_action.dart, frontend/lib/store/regatta_reducer.dart
Had this implemented yesterday but had a problem with the e2e test, that's fixed now.
=> Implement a delete action.

frontend/.analysis_options, frontend/lib/app_component.css, frontend/lib/app_component.dart, frontend/lib/app_component.html, frontend/lib/components/app_header/app_header.css, frontend/lib/components/app_header/app_header.dart, frontend/lib/components/app_header/app_header.html, frontend/lib/services/firebase_service.dart, frontend/pubspec.yaml, frontend/web/index.html, frontend/web/styles.css
First introducttion of firebase, authentication works.
=> Reg 53 introduce firebase

frontend/lib/app_component.dart, frontend/lib/components/event_list_component/event_list_component.dart, frontend/lib/components/event_list_component/event_list_component.html, frontend/lib/components/navigation_bar_component/navigation_bar_component.html, frontend/lib/components/sailing_club_detail_component/sailing_club_detail_component.dart, frontend/lib/components/sailing_club_detail_component/sailing_club_detail_component.html, frontend/lib/components/sailing_club_list_component/sailing_club_list_component.dart, frontend/lib/components/sailing_club_list_component/sailing_club_list_component.html, frontend/lib/components/sailing_club_list_component/sailing_club_list_component_po.dart, frontend/lib/models/event_test.dart, frontend/lib/models/sailing_club.dart, frontend/lib/models/sailing_club_test.dart, frontend/lib/services/firebase_service.dart, frontend/lib/store/action_type.dart, frontend/lib/store/regatta_action.dart, frontend/lib/store/regatta_reducer.dart, frontend/lib/store/regatta_state.dart
This adds basic sailing club persistence. The way to add it is completely straight forward now but unfortunately a lot of code duplication. This would be a good candidate for a refactoring.
=> Reg 57 add sailing club persistence

frontend/lib/app_component.dart, frontend/lib/components/boat_detail_component/boat_detail_component.dart, frontend/lib/components/boat_detail_component/boat_detail_component.html, frontend/lib/components/boat_list_component/boat_list_component.dart, frontend/lib/components/boat_list_component/boat_list_component.html, frontend/lib/components/boat_list_component/boat_list_component_po.dart, frontend/lib/components/event_list_component/event_list_component.dart, frontend/lib/components/event_list_component/event_list_component.html, frontend/lib/components/navigation_bar_component/navigation_bar_component.html, frontend/lib/components/sailing_club_detail_component/sailing_club_detail_component.dart, frontend/lib/components/sailing_club_detail_component/sailing_club_detail_component.html, frontend/lib/components/sailing_club_list_component/sailing_club_list_component.dart, frontend/lib/components/sailing_club_list_component/sailing_club_list_component.html, frontend/lib/components/sailing_club_list_component/sailing_club_list_component_po.dart, frontend/lib/models/boat.dart, frontend/lib/models/boat_test.dart, frontend/lib/models/event_test.dart, frontend/lib/models/sailing_club.dart, frontend/lib/models/sailing_club_test.dart, frontend/lib/services/firebase_service.dart, frontend/lib/store/action_type.dart, frontend/lib/store/regatta_action.dart, frontend/lib/store/regatta_reducer.dart, frontend/lib/store/regatta_state.dart
=> Reg 58 add boat persistence

frontend/lib/components/event_detail_component/event_detail_component.dart, frontend/lib/components/event_detail_component/event_detail_component.html
Now the dropdown works, except for styling. See http://regatta-17147.firebaseapp.com/ (after login).
=> Implement organizer change.

.travis.yml, frontend/Makefile, frontend/lib/app_component.dart, frontend/lib/app_component.html
=> Reg 61 better version number

tmux.sh
=> REG 62 Specific windows for angular frontend dev

frontend/lib/components/event_detail_component/event_detail_component.html
Works great but the style is a bit off.
=> Use the material-dropdown-select component.

frontend/lib/app_component.css, frontend/lib/app_component.html, frontend/lib/components/event_detail_component/event_detail_component.dart, frontend/lib/components/event_detail_component/event_detail_component.html, frontend/lib/components/event_list_component/event_list_component.html, frontend/lib/models/event.dart, frontend/lib/models/event_test.dart
Now it seems to be ok and the code is not too ugly.
=> Implement searchable dropdown

frontend/lib/components/event_detail_component/event_detail_component.css, frontend/lib/components/event_detail_component/event_detail_component.html
Just a small style change to make it look better.
=> Make the dropdown look nice wit ha label.

Makefile, database.rules.bolt, database.rules.json, frontend/lib/components/event_detail_component/event_detail_component.dart, frontend/lib/components/event_detail_component/event_detail_component.html, frontend/lib/components/event_list_component/event_list_component.dart, frontend/lib/components/event_list_component/event_list_component.html, frontend/lib/components/navigation_bar_component/navigation_bar_component.dart, frontend/lib/components/sailing_club_detail_component/sailing_club_detail_component.dart, frontend/lib/components/sailing_club_detail_component/sailing_club_detail_component.html, frontend/lib/components/sailing_club_list_component/sailing_club_list_component.dart, frontend/lib/models/person.dart, frontend/lib/services/firebase_service.dart, frontend/lib/store/action_type.dart, frontend/lib/store/regatta_action.dart, frontend/lib/store/regatta_reducer.dart, frontend/lib/store/regatta_state.dart
Ok it now more or less works, just the logout does not yet set the currentUser to null!?
=> Implement join button

frontend/.idea/codeStyleSettings.xml, frontend/.idea/codeStyles/codeStyleConfig.xml, frontend/.idea/frontend.iml, frontend/Makefile, frontend/lib/components/boat_detail_component/boat_detail_component.dart, frontend/lib/components/boat_list_component/boat_list_component.dart, frontend/lib/components/event_detail_component/event_detail_component.dart, frontend/lib/components/event_list_component/event_list_component.dart, frontend/lib/components/event_list_component/event_list_component.html, frontend/lib/components/event_list_component/event_list_component_po.dart, frontend/lib/components/sailing_club_detail_component/sailing_club_detail_component.dart, frontend/lib/components/sailing_club_list_component/sailing_club_list_component.dart, frontend/lib/services/firebase_service.dart, frontend/lib/store/action_type.dart, frontend/lib/store/regatta_action.dart, frontend/lib/store/regatta_reducer.dart, frontend/lib/store/regatta_state.dart, frontend/lib/store/regatta_store.dart, frontend/test/event_list_test.dart
First working version of pagination. Needs refactoring, cleanup and tests and checks for corner cases, but the implementation works already.
=> Implement event pagination
